//TODO CREATE DIFFERENT SIZED CARD BACKS FOR DIFFERENT SIZED SCREENS
//TODO CREATE MENU
//TODO SET CARDS UP FOR PLAY
//TODO SHUFFLE CARDS
//TODO SET UP TIMER
//TODO UPDATE STATS/SAVE STATS
//TODO DETECT SELECTION/MATCHES